### ISSUE TITLE
On Pubsites, can't leave a rating - many instances are gone

### ISSUE THREAD

**Issue by Cassolotl** [redmatrix/redmatrix#314]
https://redmatrix.me/pubsites

Many instances are gone, so I would like to mark them as such or leave a rating to say so, but I can't see a way or someone to contact about this.

**Comment by redmatrix** [comment]
Ratings can be made by any member, and can be made from the /pubsites page of their own hub. If for some reason ratings are not available on your own hub you can visit 

https://redmatrix.me/pubsites?f=&zid=abc@xyz.com

replace abc@xyz.com with your actual webbie/reddress,

**Comment by Lottiotta** [comment]
So there is no way for me to leave low ratings for dead instances, or otherwise mark them as dead?

**Comment by redmatrix** [comment]
Sure there is. See my previous comment. If the issue is that you are not a member, we do not allow ratings from unknown people as we are not friendly to spammers.

**Comment by jeroenpraat** [comment]
@Cassolotl This issue is closed because Redmatrix evolved into [Hubzilla](https://github.com/redmatrix/hubzilla). When this is still an issue in the most recent version of Hubzilla, please recreate this issue [over there](https://github.com/redmatrix/hubzilla/issues). We're sorry for any inconvenience this will maybe give you.
