### ISSUE TITLE
Permissions seem wrongfully applied in process_delivery

### ISSUE THREAD

**Issue by solstag** [redmatrix/redmatrix#328]
From what I understand of the code and from what I saw in tests, this (zot.php:process_delivery):

		$perm = (($arr['mid'] == $arr['parent_mid']) ? 'send_stream' : 'post_comments');
...

		if((! perm_is_allowed($channel['channel_id'],$sender['hash'],$perm)) && (! $tag_delivery) && (! $local_public)) {
			logger("permission denied for delivery to channel {$channel['channel_id']} {$channel['channel_address']}");
			$result[] = array($d['hash'],'permission denied',$channel['channel_name'] . ' <' . $channel['channel_address'] . '@' . get_app()->get_hostname() . '>',$arr['mid']);
			continue;
		}

Results in a post from a contact, accepted by me, never getting comments from people who are not my contacts.

I don't think this is the desired outcome, and in any case we are checking against a permission that says "can other people comment on my posts" to allow comments to posts by other people whom I've allowed to send me their stream - not my own posts.

I would change the above so that the permissions check only applies if the post is a top level post.or a comment on a post owned by me.

What do others think? Cheers!

**Comment by redmatrix** [comment]
We had that issue come up in another place. I'll investigate further to verify it applies here and see how to fix it.

**Comment by redmatrix** [comment]
Yeah I'm not sure this issue is valid. We're checking if the sender is allowed to send you comments. The sender is usually the owner of the conversation. We aren't checking the author - who we may not know. If we are the owner of the conversation this also works because the sender will be one of our connections. 

Note there were some missing Diaspora comments for the last few days due to an unrelated bug.

**Comment by jeroenpraat** [comment]
@solstag This issue is closed because Redmatrix evolved into [Hubzilla](https://github.com/redmatrix/hubzilla). When this is still an issue in the most recent version of Hubzilla, please recreate this issue [over there](https://github.com/redmatrix/hubzilla/issues). We're sorry for any inconvenience this will maybe give you.
