### ISSUE TITLE
Deleted channels: redmatrix still polls on their behalf and exposes their past existence

### ISSUE THREAD

**Issue by solstag** [redmatrix/redmatrix#329]
My account has a deleted channel.

It only shows up in the database, with a deletion date of over a year ago.

However, I've noticed that it is still getting its contacts streams delivered to it.

Less important but still significant, if I open "[basurl]/channel/name", I get a different corner notification than for a channel that never existed, exposing its past existence.

**Comment by jeroenpraat** [comment]
@solstag This issue is closed because Redmatrix evolved into [Hubzilla](https://github.com/redmatrix/hubzilla). When this is still an issue in the most recent version of Hubzilla, please recreate this issue [over there](https://github.com/redmatrix/hubzilla/issues). We're sorry for any inconvenience this will maybe give you.
