### ISSUE TITLE
Deletion of comment in a forum not propagating back to original poster

### ISSUE THREAD

**Issue by solstag** [redmatrix/redmatrix#330]
1. Comment on somebody else's post on a forum wall. (In my test the post had @+ tagged the forum, not posted directly on the forum's wall.)
2. Delete the comment.
3. Comment gets deleted from your stream, from forum's stream, from forum followers' streams
5. Comment does not get deleted from the original poster's stream or from his followers'

**Comment by solstag** [comment]
Tested in the following setup:
Alice posts privately to Forum and Bob
Forum delivers privately to Chelsea and Doris
Chelsea comments on her copy
Comment gets relayed to everyone
Chelsea deletes her copy of her comment
Comment gets deleted for Forum and Doris
Comment does not get deleted for Alice and Bob

**Comment by jeroenpraat** [comment]
@solstag This issue is closed because Redmatrix evolved into [Hubzilla](https://github.com/redmatrix/hubzilla). When this is still an issue in the most recent version of Hubzilla, please recreate this issue [over there](https://github.com/redmatrix/hubzilla/issues). We're sorry for any inconvenience this will maybe give you.
