### ISSUE TITLE
Compatible with Friendica

### ISSUE THREAD

**Issue by mama21mama** [redmatrix/redmatrix#334]
I try to follow this account from my redmatrix.

mama21mama@friendica.ml

my redmatrix. mama21mama@redmatrix.ml

He tells me this warning.
`Protocol disabled.`

**Comment by redmatrix** [comment]
Redmatrix and Friendica communicate with each other using the Diaspora protocol. We used this because that provides access to both networks with one codebase, and Friendica's DFRN has a number of problems that I didn't wish to perpetuate in Redmatrix. You need to enable Diaspora communications from the Redmatrix admin/site page and it should work.

**Comment by mama21mama** [comment]
Gracias.

**Comment by redmatrix** [comment]
De nada.
