### ISSUE TITLE
cloud capacity limit

### ISSUE THREAD

**Issue by mama21mama** [redmatrix/redmatrix#338]
I know how I can limit the capacity of each cloud user.

**Comment by redmatrix** [comment]
We do this with service classes. Please ask this question on one of the development channels as I don't have a configuration in front of me currently (my site does not have limits).

**Comment by habeascodice** [comment]
you'll need to update to commit f7731d7
visit yoursite/help/service_classes
let me know if you need more detail

**Comment by redmatrix** [comment]
@habeascodice Thanks - that's a definite improvement over the way we've been doing it.

**Comment by mama21mama** [comment]
the only problem I have 98gb free. Otherwise it may merely stop at some point.

**Comment by habeascodice** [comment]
I added the capability to set existing users service class. git pull the latest code to use.
still goto yoursite.com/help/service_classes for the full instructions

example:
util/service_class class1 photo_upload_limit 100000000
util/service_class class1 attach_upload_limit 100000000
util/service_class --account=2 class1

creates new class called class1 with maximum photos of 100MB and maximum cloud/DAV of 100MB, then sets account #2 to class1. You can verify from the admin/users page.

There is currently no way to set overrall system limits, so it is still possible to run out of space if you oversubscribe. This is an issue that is being addressed in a future update that is still being written.

**Comment by mama21mama** [comment]
I get the legend:
Page not found.

There is no way of knowing whether worked.

**Comment by redmatrix** [comment]
Which page? 

help/service_classes (?)

That's a documentation page. If it's not available, please make sure you've updated your code. The others are shell commands which you use to interact with the service_class settings.

**Comment by mama21mama** [comment]
Please explain the missing documentation.

The documentation must say that one should pocicionarce in the folder where is housed redmatrix. That information is not.

One should be guessing where to run it.

Now I understood without documentation.

1 example from the bash terminal
cd /var/www/redmatrix.ml

2
$ php util/service_class class1 photo_upload_limit 100000000

work

**Comment by jeroenpraat** [comment]
https://redmatrix.ml/help/service_classes is working, but I see you using a self signed certificate. As you can read in the Install text, we ask you to use a global supported certificate.

**Comment by mama21mama** [comment]
It is safer, self-signed

**Comment by jeroenpraat** [comment]
For us it's on old discussion. For Redmatrix it is not efficient. In the install.txt: 
"You SHOULD use SSL. If you use SSL, you MUST use a
"browser-valid" certificate.  You MUST NOT use self-signed certificates!

Please test your certificate prior to installation. A web tool for testing your
certificate is available at "http://www.digicert.com/help/". When visiting your
site for the first time, please use the SSL ("https://") URL if SSL is
available. This will avoid problems later. The installation routine will not
allow you to use a non browser-valid certificate.

This restriction is incorporated because public posts from you may contain 
references to images on your own hub. Other members viewing their stream on
other hubs will get warnings if your certificate is not trusted by their web
browser. This will confuse many people because this is a decentralised network
and they will get the warning about your hub while viewing their own hub and may 
think their own hub has an issue. These warnings are very technical and scary to 
some folks, many of whom will not know how to proceed except to follow the browser
advice. This is disruptive to the community. That said, we recognise the issues
surrounding the current certificate infrastructure and agree there are many
problems, but that doesn't change the requirement. 

Free "browser-valid" certificates are available from providers such as StartSSL. 
"

**Comment by mama21mama** [comment]
background on certificates

http://www.itpro.co.uk/635833/certificate-authority-confirms-hack-after-gmail-attack
http://arstechnica.com/security/2011/09/comodo-hacker-i-hacked-diginotar-too-other-cas-breached/
http://resources.infosecinstitute.com/cybercrime-exploits-digital-certificates/
http://arstechnica.com/security/2011/09/comodo-hacker-i-hacked-diginotar-too-other-cas-breached/

**Comment by redmatrix** [comment]
I'm aware of the issues. We require valid certs for you to be a member of our network (if you use SSL). It is not optional or negotiable. Self-signed certs will not work correctly within our network.

**Comment by mama21mama** [comment]
A platform can not make you not use self-signed certificates. where freedom is.

**Comment by redmatrix** [comment]
This isn't about certs and it isn't about freedom. They do not work in a decentralised communication network. If you have a problem with this, take it up with the browser vendors. My software is not popping up warning dialogues every time it encounters a self-signed cert. Theirs is.

**Comment by mama21mama** [comment]
Well there.
