### ISSUE TITLE
no puedo seguir desde diaspora

### ISSUE THREAD

**Issue by mama21mama** [redmatrix/redmatrix#345]
Hola,
pasa algo raro no me deja seguir la cuenta redmatrix-es@redmatrix.ml

desde joindiaspora.

**Comment by redmatrix** [comment]
Diaspora requires valid SSL certs.

**Comment by mama21mama** [comment]
Si puedo seguir desde diaspora a mama21mama@redmatrix.ml [cuenta normal]
redmatrix-es@redmatrix.ml [cuenta foro]

**Comment by redmatrix** [comment]
It is very difficult to troubleshoot something for which there is not an adequate description or supporting information. Was a webfinger attempted from joindiaspora to the Redmatrix channel and/or is the channel known on joindiaspora? Was a friend request sent? What do your site logs say about these events? What were the results in the UI and/or error messages on either side? Due to past history with Diaspora communications, we don't consider this to be a Redmatrix issue unless you can show that communication actually reached Redmatrix and that Redmatrix provided incorrect responses; and the lack of a valid SSL cert is the very first thing that needs fixing before we can troubleshoot it further. Unfortunately, if you present such an issue to Diaspora they will probably tell you that a) valid certs are required, and b) joindiaspora.com is a large pod that often has "federation issues" (in other words, communications randomly fail for no apparent reason).

**Comment by mama21mama** [comment]
Desde diaspora a Redmatrix funciona.
![](http://upimage.mamalibre.com.ar/up/443febde82c5fc71a680788e48b4daaf.png)

Cuenta normal.

Y desde redmatrix he agregado mama21mama@joindiaspora.com  perfectamente.

Conexión mutua.  log  > http://text0.tk/1748


El problema:

Desde diaspora, no me deja seguir esta cuenta redmatrix-es@redmatrix.ml [forum]

Diaspora no la encuentra. 

![](http://upimage.mamalibre.com.ar/up/71b79f1dcfed0e8071d8867140ade6f0.png)

**Comment by redmatrix** [comment]
That's a known Diaspora bug which affects large pods more than small pods. If you keep attempting it, eventually it "might" work. I use the word "might" because Diaspora uses strict SSL checking and without a valid cert there's a good chance it will never work. So you can keep trying once a day. It has been known to take up to three weeks of trying before it works. If it still hasn't been recognised a month from now, it's probably because of the cert. Why it worked without a valid cert is unknown to me, as this is unsupported and has never worked before. In any event, this is not a redmatrix bug. The probe never made it to your redmatrix server. This is a Diaspora bug.
