### ISSUE TITLE
Community tags lost on update

### ISSUE THREAD

**Issue by solstag** [redmatrix/redmatrix#350]
Code that causes item updates ignores community tags, which are then lost if the item is updated. The main example is item_post().

I haven't look in detail and am not sure if we can properly distinguish body tags from community tags, which would be required to fix this.

**Comment by solstag** [comment]
Ok, looking at the database now I see that we make no distinction between body tags and pure tags.
There is a term type field though, which currently has the same type for body tags and pure tags.
Would changing this be welcome? I think it is expected that pure terms will be preserved when a post is edited. We could later add a box to the post editor to edit the pure terms of a post, but even that would benefit from distinguishing body and pure terms.

**Comment by redmatrix** [comment]
That makes sense. We can't preserve the community tags because we re-generate the tags when editing the post and they aren't referenced in the body. The same probably applies to "file_as" (TERM_FILE) activities. Changing them to another type is probably the best way of knowing that they aren't referenced in the body so they can be saved separately.

**Comment by jeroenpraat** [comment]
@solstag This issue is closed because Redmatrix evolved into [Hubzilla](https://github.com/redmatrix/hubzilla). When this is still an issue in the most recent version of Hubzilla, please recreate this issue [over there](https://github.com/redmatrix/hubzilla/issues). We're sorry for any inconvenience this will maybe give you.
