### ISSUE TITLE
Exporting and importing terms (tags)

### ISSUE THREAD

**Issue by solstag** [redmatrix/redmatrix#351]
It seems that exporting and importing ignores terms.
Body tags could be regenerated, but currently aren't.
All community tags from the exporter hub are lost.

**Comment by jeroenpraat** [comment]
@solstag This issue is closed because Redmatrix evolved into [Hubzilla](https://github.com/redmatrix/hubzilla). When this is still an issue in the most recent version of Hubzilla, please recreate this issue [over there](https://github.com/redmatrix/hubzilla/issues). We're sorry for any inconvenience this will maybe give you.
