### ISSUE TITLE
directory rating count not correct

### ISSUE THREAD

**Issue by git-marijus** [redmatrix/redmatrix#358]
Some channels seem to have significant differences in rating counts as shown in the directory.
For example channel one shows a rating count of 1 in the directory but actually has 9 ratings - looking at it from my hub. The actual rating count (looking at /ratings/hash) differs from hub to hub...

**Comment by jeroenpraat** [comment]
@git-marijus This issue is closed because Redmatrix evolved into [Hubzilla](https://github.com/redmatrix/hubzilla). When this is still an issue in the most recent version of Hubzilla, please recreate this issue [over there](https://github.com/redmatrix/hubzilla/issues). We're sorry for any inconvenience this will maybe give you.
