### ISSUE TITLE
RedMatrix 2.6 - problem SVG vs JPEG/PNG in cloud as channel background image

### ISSUE THREAD

**Issue by HaakonME** [redmatrix/redmatrix#361]
This problem is not new, but I have managed to narrow it down. If a channel background image is an SVG-file in the channel cloud, then it must be manually deleted and reuploaded to the same place in the channel cloud after each code update to display, i.e. SVG-files are not safe in the cloud.

Examples
OK: https://d-kommune.rhcloud.com/channel/flldrammen - bitmap background image (JPEG/PNG) - updating the code results in no problems, the background image is in the cloud, the display settings are kept, and the background image displays.

NOT OK: https://d-kommune.rhcloud.com/channel/drammen - vector background image (SVG) - updating the code results in the background image (SVG) is in the cloud, the display settings are kept, but the background image does not dispay. SVG must be deleted from the cloud and reuploaded to the cloud, and then it appears instantly.

**Comment by jeroenpraat** [comment]
@HaakonME This issue is closed because Redmatrix evolved into [Hubzilla](https://github.com/redmatrix/hubzilla). When this is still an issue in the most recent version of Hubzilla, please recreate this issue [over there](https://github.com/redmatrix/hubzilla/issues). We're sorry for any inconvenience this will maybe give you.
