### ISSUE TITLE
Tags get multiplied on delivery (some kind of looping)

### ISSUE THREAD

**Issue by solstag** [redmatrix/redmatrix#364]
Tag a post you got from a forum whose author you also have as a connection (this will happen if they sent it privately to the forum).

Post gets tagged multiple multiple multiple times.

There might be some kind of multiple route check that we're skipping for tags but we have for comments.

**Comment by jeroenpraat** [comment]
@solstag This issue is closed because Redmatrix evolved into [Hubzilla](https://github.com/redmatrix/hubzilla). When this is still an issue in the most recent version of Hubzilla, please recreate this issue [over there](https://github.com/redmatrix/hubzilla/issues). We're sorry for any inconvenience this will maybe give you.
