### ISSUE TITLE
New hub - notification timestamps makes no sense when posts start arriving

### ISSUE THREAD

**Issue by HaakonME** [redmatrix/redmatrix#372]
My new RedMatrix-hub - https://red-mor.rhcloud.com/ - went live tonight. 

I imported the haakon-channel from Parlementum.net, but made sure to not import any posts. However, as the poller started a slew of old posts - over a year old - from other people started arriving in my network stream. 

The issue is with the notifications - these are reported according to the time they arrived at the new hub, not the timestamp in the arriving posts at all. I worry that I might miss real new items.

**Comment by redmatrix** [comment]
If you are referring to email nofications I recommend the mailhost addon. It designates a single hub which is used for email notifications.

**Comment by HaakonME** [comment]
No, the notifications under https://domain/notifications/system .

**Comment by jeroenpraat** [comment]
@HaakonME This issue is closed because Redmatrix evolved into [Hubzilla](https://github.com/redmatrix/hubzilla). When this is still an issue in the most recent version of Hubzilla, please recreate this issue [over there](https://github.com/redmatrix/hubzilla/issues). We're sorry for any inconvenience this will maybe give you.
