### ISSUE TITLE
Require submit button to update collection membership

### ISSUE THREAD

**Issue by anaqreon** [redmatrix/redmatrix#384]
In the connection editor, the current behavior is to immediately toggle the connection's membership in the collection when the check box is toggled. For consistency, this action should not be applied until the user presses the submit button.

**Comment by anaqreon** [comment]
The javascript https://github.com/redmatrix/redmatrix/blob/master/view/js/main.js#L1038 calls https://github.com/redmatrix/redmatrix/blob/master/mod/contactgroup.php
directly. Perhaps this should go in another collapsible settings panel like the permissions settings in https://github.com/redmatrix/redmatrix/blob/master/view/tpl/abook_edit.tpl?

**Comment by anaqreon** [comment]
Alternatively, when clicked, the checkbox could be replaced by an animated "busy" icon like the radial spinner that displays while posts are loading, and then when the action completes it is replaced by the toggled checkbox..

**Comment by jeroenpraat** [comment]
@anaqreon This issue is closed because Redmatrix evolved into [Hubzilla](https://github.com/redmatrix/hubzilla). When this is still an issue in the most recent version of Hubzilla, please recreate this issue [over there](https://github.com/redmatrix/hubzilla/issues). We're sorry for any inconvenience this will maybe give you.
