### ISSUE TITLE
Red to Red connector

### ISSUE THREAD

**Issue by hfroese** [redmatrix/redmatrix#387]
Since two days? postings on Red are nor forwarded to Hubzilla anymore.
Hubzilla to Red is working.

**Comment by jeroenpraat** [comment]
@hfroese This issue is closed because Redmatrix evolved into [Hubzilla](https://github.com/redmatrix/hubzilla). When this is still an issue in the most recent version of Hubzilla, please recreate this issue [over there](https://github.com/redmatrix/hubzilla/issues). We're sorry for any inconvenience this will maybe give you.
