### ISSUE TITLE
jQuery timeAgo translation strings.

### ISSUE THREAD

**Issue by Razlo** [redmatrix/redmatrix#392]
The translation strings should have a comment on how to translate them properly. Maybe a a block comment in the page linked by Transifex would have helped me, and spared me some time.

https://github.com/redmatrix/redmatrix/blob/master/include/js_strings.php

However, I have a question left: what does "timeago.numbers" mean?

**Comment by jeroenpraat** [comment]
@Razlo This issue is closed because Redmatrix evolved into [Hubzilla](https://github.com/redmatrix/hubzilla). When this is still an issue in the most recent version of Hubzilla, please recreate this issue [over there](https://github.com/redmatrix/hubzilla/issues). We're sorry for any inconvenience this will maybe give you.
