### ISSUE TITLE
Edit option doesn't translate Markdown well

### ISSUE THREAD

**Issue by jasrandal** [redmatrix/redmatrix#396]
A post created in Hubzilla using Markdown appears as bbcode when later editing that post. Lists are not converted properly from Markdown into bbcode in the Edit feature.

**Comment by jeroenpraat** [comment]
@jasrandal This issue is closed because Redmatrix evolved into [Hubzilla](https://github.com/redmatrix/hubzilla). When this is still an issue in the most recent version of Hubzilla, please recreate this issue [over there](https://github.com/redmatrix/hubzilla/issues). We're sorry for any inconvenience this will maybe give you.
