### ISSUE TITLE
cropper not loading on createcafe.net

### ISSUE THREAD

**Issue by h4ck3rm1k3** [redmatrix/redmatrix#398]
from the page : https://createcafe.net/profile_photo
GET 
https://createcafe.net/library/cropper/lib/scriptaculous.js [HTTP/1.1 403 Forbidden 78ms]
GET 
https://createcafe.net/library/cropper/lib/scriptaculous.js [HTTP/1.1 403 Forbidden 34ms]
ReferenceError: Draggable is not defined cropper.js:19:0
TypeError: $(...).ready is not a function profile_photo:136:0
TypeError: $(...).ready is not a function main.js:1136:0
TypeError: $(...) is undefined redbasic.js:6:1
TypeError: Cropper is undefined profile_photo:451:2

**Comment by redmatrix** [comment]
This looks like a file permission problem. 

Is library/cropper/lib (and all of its files) world readable - or at least readable by the web server?

**Comment by h4ck3rm1k3** [comment]
I dont know, it seems that there is no way to contact the owner of the server. It would be nice to have that feature.

**Comment by jeroenpraat** [comment]
@h4ck3rm1k3 This issue is closed because Redmatrix evolved into [Hubzilla](https://github.com/redmatrix/hubzilla). When this is still an issue in the most recent version of Hubzilla, please recreate this issue [over there](https://github.com/redmatrix/hubzilla/issues). We're sorry for any inconvenience this will maybe give you.
