### ISSUE TITLE
Bug report to site owner

### ISSUE THREAD

**Issue by h4ck3rm1k3** [redmatrix/redmatrix#399]
It would be nice to have a report bug to site maintainer, not only report bug to the redmatrix in the webapp.

**Comment by redmatrix** [comment]
Here is the maintainer:

https://createcafe.net/channel/iko

**Comment by h4ck3rm1k3** [comment]
that is for issue #398 , I am asking for a feature in redmatix to report a site issue to the owner.

**Comment by jeroenpraat** [comment]
@h4ck3rm1k3 This issue is closed because Redmatrix evolved into [Hubzilla](https://github.com/redmatrix/hubzilla). When this is still an issue in the most recent version of Hubzilla, please recreate this issue [over there](https://github.com/redmatrix/hubzilla/issues). We're sorry for any inconvenience this will maybe give you.
