### ISSUE TITLE
Changing profile photo not working and Friends Profiles Pictures not show

### ISSUE THREAD

**Issue by royalterra** [redmatrix/redmatrix#400]
Hi I read the last bug closed for Changing profile photo not working but still that not work I have 2 installations in different domains with SSL and in both some users you add us friend not show the profile picture is only the icon of error picture because not found . That error is in both installations and in one installation one user can upload picture crop and setup us profile picture but the picture never change.
Test difference browsers and networks not make different

**Comment by jeroenpraat** [comment]
@royalterra This issue is closed because Redmatrix evolved into [Hubzilla](https://github.com/redmatrix/hubzilla). When this is still an issue in the most recent version of Hubzilla, please recreate this issue [over there](https://github.com/redmatrix/hubzilla/issues). We're sorry for any inconvenience this will maybe give you.
