### ISSUE TITLE
Loops

### ISSUE THREAD

**Issue by royalterra** [redmatrix/redmatrix#401]
In directory is the block Suggestions if you click in connect normally will connect and add the channel but if the Person or Channel you see there is already in you list you will get "This web page has a redirect loop ERR_TOO_MANY_REDIRECTS " 
You get also to many redirects and the page crash if the other server have any bad configuration and not connect

**Comment by jeroenpraat** [comment]
@royalterra This issue is closed because Redmatrix evolved into [Hubzilla](https://github.com/redmatrix/hubzilla). When this is still an issue in the most recent version of Hubzilla, please recreate this issue [over there](https://github.com/redmatrix/hubzilla/issues). We're sorry for any inconvenience this will maybe give you.
