### ISSUE TITLE
Feature Request: Support for remote subscribe

### ISSUE THREAD

**Issue by annando** [redmatrix/redmatrix#405]
In Friendica you can add remote profiles by entering your handle on the foreign page.

Means: You visit a profile on the Friendica server A. You enter your handle (from server B) on the page "/dfrn_request". You are redirected to your server B to add the contact.

This works with Friendica and with OStatus contacts. It will work with the upcoming Diaspora release as well. It would be great if Hubzilla/Redmatrix would support this as well.

All you have to do is to is to add a line like this in your webfinger:
````
<Link rel="http://ostatus.org/schema/1.0/subscribe" template="https://pirati.ca/follow?url={uri}"/>
````

If this would be done, people from Hubzilla/Redmatrix could easily add people from Friendica.

**Comment by jeroenpraat** [comment]
@annando This issue is closed because Redmatrix evolved into [Hubzilla](https://github.com/redmatrix/hubzilla). When this is still an issue in the most recent version of Hubzilla, please recreate this issue [over there](https://github.com/redmatrix/hubzilla/issues). We're sorry for any inconvenience this will maybe give you.

**Comment by annando** [comment]
I opened a similar issue in Hubzilla which was closed without a comment: https://github.com/redmatrix/hubzilla/issues/241

**Comment by jeroenpraat** [comment]
No it was not closed without a comment. It was referenced by a commit. So this one is fixed.

**Comment by annando** [comment]
Oh, okay. Great.
